config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'my-articles', to: 'articles#user_articles'
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_out_path_for(_scope)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_page, only: [:show, :edit]

  def user_articles
    @articles = Article.where(user_id: current_user.id)
  end

  def index
    @articles = Article.all
  end

  def show
    # @article = Article.find_by(id: params[:id])
  end


  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @article = Article.find(params[:id])

    unless @article.user.id == current_user.id
      redirect_to @article, notice: "You can't edit this article"
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def correct_page
    @article = Article.find_by(id: params[:id])
    redirect_to root_path, notice: 'Page not found' if @article.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    values = comment_params
    values['commenter'] = current_user.name
    @article.comments.create(values)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :status)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="mt-2">
  <h1>Articles!</h1>

  this blog has <strong><%= @articles.public_count %></strong> articles and counting! 
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li><%= link_to "#{article.user.name} - #{article.title}" , article %></li>
    <% end %>
  <% end %>

  <%= link_to "New Article", new_article_path %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<span style="display: flex;align-items: baseline;"> 
  <h1>
    <%= @article.title %>
    <h4 style="margin-left: 1%">
      <i> by <%= @article.user.name %></i>
    </h4>
  </h1>
</span>

<p><%= @article.body %></p>

<% if user_signed_in? %>
  <% if current_user.id == @article.user.id %>
    <ul>
      <li><%= link_to "Edit", edit_article_path(@article) %></li>
      <li><%= link_to "Destroy", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %></li>
    </ul>
  <% end %>
<% end %>
  

<h5>Add a comment:</h5>
<%= render 'comments/form' %>

<h2>Comments</h2>
<%= render @article.comments.order(created_at: :desc) %>

app/views/articles/user_articles.html.erb
<% unless @articles.empty? %>
  <% @articles.each do |article| %>
    <h1><%= link_to article.title, article %></h1>
  <% end %>
<% else %>
  <h4>No articles yet? Let's <%= link_to 'change', new_article_path %> that!</h4>
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong><%= comment.commenter %>:</strong>
    <%= comment.body %> 
    <i style="color: var(--bs-gray-700);">at <%= time_ago_in_words(comment.created_at) %></i>
  </p>

  <% link_to "Delete comment", comment.article, data: {
                              turbo_method: :delete,
                              turbo_confirm: "Are you sure?"
                            } %>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mangrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap styels -->
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" %>

    <!-- Rails styles -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <main class="container-fluid">
      <%= render 'shared/alerts', alert: notice, style: 'danger' %>
      <%= render 'shared/alerts', alert: alert, style: 'warning' %>
      <%= yield %>
    </main>

    <!-- Bootstrap script tag-->
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if alert %>
  <div class="w-50 mt-2 m-auto alert alert-<%= style %> alert-dismissible fade show" role="alert">
  <p><%= alert %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="p-3 bg-dark text-white">
  <div class="d-flex flex-wrap align-items-center justify-content-between ">
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><%= link_to "Home", root_path, class: "nav-link px-2 text-white" %></li>
    </ul>

  <% if user_signed_in? %>

    <div class="btn-group">
      <div type="button" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <%= image_tag url_for(current_user.avatar), size: "45x45", style: "border-radius: 50%" %>
      </div>
      <ul class="dropdown-menu">
        <li><%= link_to "My Articles", my_articles_path, class: "dropdown-item" %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
        <li><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  <% else %>
    <div class="text-end">
      <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light me-2" %>
      <%= link_to "Register", new_user_registration_path, class: "btn btn-warning" %>
    </div>
  </div>
  <% end %>
</header>